### ISSUE TITLE
Navigation bar prototype

### ISSUE THREAD

**Issue by novvac** [novvac/news-website#5]
Create very minimalistic temporary navigation bar on left side of web app.
This navigation bar will be for mobile phones.

### To-do
- [x] Create navigation bar
- [x] Connect with links from vuex store
- [x] Hide menu on small screens and show up navigation bar button
- [x] Connect navigation bar to button
